name: CI

on:
  - push
  - pull_request

# TODO: Add the deploy if needed
jobs:
  test-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.10.1.763
          lein: 2.9.3
          bb: 0.8.2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'

      - name: Run JVM tests
        run: bb test:jvm

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.10.1.763
          lein: 2.9.3
          bb: 0.8.2

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'

      - name: Run node tests
        run: bb test:node

  test-native:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.10.1.763
          lein: 2.9.3
          bb: 0.8.2

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run node tests
        run: bb test:native

  test-self-hosted:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.10.1.763
          lein: 2.9.3
          bb: 0.8.2

      - name: Install planck
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install planck

      - name: Run self-hosted tests
        run: bb test:self-hosted

  test-libsci:
    # Compile and test libsci across all OSs.
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '11'
          components: 'native-image'

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          bb: '1.0.165'
          lein: '2.9.10'

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn', 'project.clj') }}
          restore-keys: cljdeps-

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Compile libsci and example programs
        run: |
          bb libsci:compile-all

      - name: Test libsci example programs
        run: |
          bb libsci:test

